config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'good_weeks#index'
  resources :good_weeks, only: :index
  get :current_week, to: 'good_weeks#current_week'
  get 'week/:year/:week', to: 'good_weeks#show', as: 'week'
  resources :books
  resources :people
  resources :good_weeks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :good_weeks, join_table: 'books_good_weeks'
  validates :name, presence: :true
end

app/models/good_week.rb
class GoodWeek < ApplicationRecord
  validates :monday, presence: true
  belongs_to :user
  has_and_belongs_to_many :books, join_table: 'books_good_weeks'
  has_and_belongs_to_many :persons

  def self.find_by_number_of_year_and_week(year, week)
    monday = Date.commercial(year.to_i, week.to_i, 1)
    self.find_by_monday(monday)
  end

  def name
    "#{number_of_year} week #{year}"
  end

  def number_of_year
    monday.cweek
  end

  def sunday
    monday.end_of_week
  end

  def year
    monday.year
  end
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :good_weeks
  validates :fio, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :good_weeks

  def author_of?(object)
    id == object.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_weeks, only: [:update, :create]
  before_action :load_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.where(user: current_user)
  end

  def show
    authorize @book
  end

  def new
    authorize @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    authorize @book
    if @book.save
      redirect_to book_path(@book)
    end
  end

  def edit
    authorize @book
  end

  def update
    authorize @book
    if @book.update_attributes(book_params)
      redirect_to book_path(@book)
    end
  end

  def destroy
    authorize @book
    if @book.delete
      redirect_to books_path
    end
  end

  private
  def set_weeks
    return unless params[:good_week_mondays].present?
    good_week_ids = Array.new
    week_mondays = params[:good_week_mondays].split.map { |m| m.to_date }
    unless week_mondays.empty?
      week_mondays.each do |monday|
        week = GoodWeek.find_by(monday: monday, user: current_user)
        if week
          good_week_ids << week.id
        else
          if monday.monday?
            week = GoodWeek.create(monday: monday, user: current_user)
            good_week_ids << week.id
          end
        end
      end
    end
    params[:book][:good_week_ids] = good_week_ids
  end

  def book_params
    params.require(:book).permit(:name, :description, :author, :comment, :rating, good_week_ids: [])
  end

  def load_book
    @book = Book.find(params[:id])
  end
end

app/controllers/good_weeks_controller.rb
class GoodWeeksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_good_week, only: :show
  before_action :week_now, only: [:current_week, :show]

  def current_week
    @good_week = @week_now
    authorize @good_week
    render :show
  end

  def show
    redirect_to current_week_path if @week_now == @good_week
    authorize @good_week
  end

  def create
    @good_week = GoodWeek.new(good_week_params)
    @good_week.user = current_user
    if @good_week.save
      redirect_to week_path(@good_week.year, @good_week.number_of_year)
    end
  end

  def update
    @good_week = current_user.good_weeks.find_by(monday: params[:good_week][:monday]) || GoodWeek.find(params[:id])
    if @good_week.update_attributes(good_week_params)
      redirect_to week_path(@good_week.year, @good_week.number_of_year)
    end
  end

  private
  def week_now
    @week_now = GoodWeek.find_by(monday: DateTime.now.beginning_of_week.to_date)
    unless @week_now
      monday = DateTime.now.beginning_of_week
      @week_now = GoodWeek.new(monday: monday, user: current_user)
    end
  end

  def set_good_week
    @good_week = current_user.good_weeks.find_by_number_of_year_and_week(params[:year], params[:week]) if current_user
    unless @good_week
      monday = Date.commercial(params[:year].to_i, params[:week].to_i, 1)
      @good_week = GoodWeek.new(monday: monday, user: current_user)
    end
  end

  def good_week_params
    params.require(:good_week).permit(:monday, :note)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :set_weeks, only: [:update, :create]
  before_action :load_person, only: [:show, :edit, :update, :destroy]

  def index
    @persons = Person.where(user: current_user)
  end

  def show
    authorize @person
  end

  def new
    authorize @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    @person.user = current_user
    authorize @person
    if @person.save
      redirect_to people_path(@person)
    end
  end

  def edit
    authorize @person
  end

  def update
    authorize @person
    if @person.update_attributes(person_params)
      redirect_to people_path(@person)
    end
  end

  def destroy
    authorize @person
    if @person.delete
      redirect_to people_path
    end
  end

  private
  def set_weeks
    return unless params[:good_week_mondays].present?
    good_week_ids = Array.new
    week_mondays = params[:good_week_mondays].split.map { |m| m.to_date }
    unless week_mondays.empty?
      week_mondays.each do |monday|
        week = GoodWeek.find_by(monday: monday, user: current_user)
        if week
          good_week_ids << week.id
        else
          if monday.monday?
            week = GoodWeek.create(monday: monday, user: current_user)
            good_week_ids << week.id
          end
        end
      end
    end
    params[:person][:good_week_ids] = good_week_ids
  end

  def person_params
    params.require(:person).permit(:fio, :birthday, :description, :note, good_week_ids: [])
  end

  def load_person
    @person = Person.find(params[:id])
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_weeks, only: [:update, :create]
  before_action :load_person, only: [:show, :edit, :update, :destroy]

  def index
    @persons = Person.where(user: current_user)
  end

  def show
    authorize @person
  end

  def new
    authorize @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    @person.user = current_user
    authorize @person
    if @person.save
      redirect_to person_path(@person)
    end
  end

  def edit
    authorize @person
  end

  def update
    authorize @person
    if @person.update_attributes(person_params)
      redirect_to person_path(@person)
    end
  end

  def destroy
    authorize @person
    if @person.delete
      redirect_to persons_path
    end
  end

  private
  def set_weeks
    return unless params[:good_week_ids].present?
    good_week_ids = Array.new
    week_mondays = params[:good_week_mondays].split.map { |m| m.to_date }
    unless week_mondays.empty?
      week_mondays.each do |monday|
        week = GoodWeek.find_by(monday: monday, user: current_user)
        if week
          good_week_ids << week.id
        else
          if monday.monday?
            week = GoodWeek.create(monday: monday, user: current_user)
            good_week_ids << week.id
          end
        end
      end
    end
    params[:person][:good_week_ids] = good_week_ids
  end

  def person_params
    params.require(:person).permit(:fio, :birthday, :description, :note, good_week_ids: [])
  end

  def load_person
    @person = Person.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.slim
.well.col-md-4
  span class = 'glyphicon glyphicon-book'
  = simple_form_for book, defaults: { input_html: { class: 'form-control' } } do |f|
    = f.input :name
    = f.input :description
    = f.input :author
    = f.input :comment
    br
      label Weeks:
      div.weeks
        - book.good_weeks.each do |week|
          p
            = link_to week.name, week_path(week.year, week.number_of_year)
            a.close class="close-week" data-monday=week.monday [x]
    .add-weeks
      label for="weekpicker" Select new week
      input type="text" id="weekpicker" name="weekpick" class="form-control" readonly="readonly"
      a.add-week
        | Add week
        span class='glyphicon glyphicon-plus'
    = text_field_tag(:good_week_mondays, book.good_weeks.map(&:monday), class: 'hidden')
    br
    = f.button :submit, class: 'btn btn-primary'

app/views/books/edit.html.slim
= render 'book', book: @book

app/views/books/index.html.slim
= link_to 'Create book', new_book_path
br
- @books.each do |book|
  = render book

app/views/books/new.html.slim
= render 'book', book: @book

app/views/books/show.html.slim
= render 'book', book: @book

app/views/good_weeks/index.html.slim
= month_calendar do |date|
  = date

app/views/good_weeks/show.html.slim
h1
  = @good_week.name
= week_calendar number_of_weeks: 1 do |date|
  = date
div
  .well.col-md-6
    h2 Books
    - @good_week.books.each do |book|
      p= link_to book.name, book_path(book)
    = link_to 'Add Book', new_book_path(params.permit.merge({good_week_ids: [@good_week.id]}))
  .well.col-md-6
    h2 Persons
    - @good_week.persons.each do |person|
      p= link_to person.fio, people_path(person)
    = link_to 'Add Person', new_person_path(params.permit.merge({good_week_ids: [@good_week.id]}))

  .well.col-md-12
    span class = 'glyphicon glyphicon-person'
    = simple_form_for @good_week, defaults: { input_html: { class: 'form-control' } } do |f|
      = f.input :monday, as: :hidden, input_html: { value: @good_week.monday }
      = f.input :note
      br
      = f.button :submit, class: 'btn btn-primary'

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
      = link_to t('application_name'), root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li class=('active' if current_page?(:current_week))
          = link_to t('menu.current_week'), current_week_path
        li
          = link_to t('menu.calendar'), root_path
        li class=('active' if current_page?(controller: :books))
          = link_to t('menu.books'), books_path
        li class=('active' if current_page?(controller: :people))
          = link_to t('menu.persons'), people_path
      ul.nav.navbar-nav.navbar-right
        li= link_to t('menu.sign_out'), destroy_user_session_path, method: :delete

app/views/layouts/_unauth.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
      = link_to t('application_name'), root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li
      ul.nav.navbar-nav.navbar-right
        li= link_to t('menu.sign_in'), new_user_session_path, method: :get
        li= link_to t('menu.sign_up'), new_user_registration_path, method: :get

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('application_name') %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if current_user %>
        <%= render 'layouts/navbar' %>
      <% else %>
        <%= render 'layouts/unauth' %>
      <% end %>
      <div><%= yield %></div>
    </div>
  </body>
</html>

app/views/people/_person.html.slim
.well.col-md-4
  span class = 'glyphicon glyphicon-person'
  = simple_form_for person, defaults: { input_html: { class: 'form-control' } } do |f|
    = f.input :fio
    = f.input :birthday
    = f.input :description
    = f.input :note
    br
      label Weeks:
      div.weeks
        - person.good_weeks.each do |week|
          p
            = link_to week.name, week_path(week.year, week.number_of_year)
            a.close class="close-week" data-monday=week.monday [x]
    .add-weeks
      label for="weekpicker" Select new week
      input type="text" id="weekpicker" name="weekpick" class="form-control" readonly="readonly"
      a.add-week
        | Add week
        span class='glyphicon glyphicon-plus'
    = text_field_tag(:good_week_mondays, person.good_weeks.map(&:monday), class: 'hidden')
    br
    = f.button :submit, class: 'btn btn-primary'

app/views/people/edit.html.slim
= render 'person', person: @person

app/views/people/index.html.slim
= link_to 'Add person', new_person_path
br
- @persons.each do |person|
  = render person

app/views/people/new.html.slim
= render 'person', person: @person

app/views/people/show.html.slim
= render 'person', person: @person

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('calendar.week') %></th>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% good_week = GoodWeek.find_by(monday: week.first) %>
          <td>
            <% if good_week %>
              <%= link_to good_week.try(:number_of_year), week_path(good_week.year, good_week.number_of_year) %>
            <% else %>
              <%= link_to week.first.cweek ,week_path(week.first.year, week.first.cweek) %>
            <% end %>
          </td>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <!--
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>
  -->

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>